### ISSUE TITLE
Make it show .jpg and .png images when sending "hot [imageformat] meme"

### ISSUE THREAD

**Issue by iiiGerardoiii** [464bb26bac556e85b6fd6b524347b103/zuck#21]
only images with lots of replies of course.

**Comment by 464bb26bac556e85b6fd6b524347b103** [comment]
is the purpose to show it on stream, or just to get a random popular image?

**Comment by iiiGerardoiii** [comment]
It’s not necessary to show it on stream, just having the popular image posted on IRC is fine imo.

**Comment by iiiGerardoiii** [comment]
It seems the project is dead, I'm closing this.
