### ISSUE TITLE
New implements 

### ISSUE THREAD

**Issue by BlackPeopleSteal** [464bb26bac556e85b6fd6b524347b103/zuck#5]
## Dear 464bb26bac556e85b6fd6b524347b103,

 _This message is for the development team of "zuck", the following ideas are part of improving "zuck" on Rizon™._

### .help
_Output Example_
.help
**Full command list at: https://github.com/464bb26bac556e85b6fd6b524347b103/faggot.md**

### .imdb
_Output Example_
.imdb the dark knight rises
**IMDb** | The Dark Knight Rises | Year: 2012 | 8,5/10 | http://www.imdb.com/title/tt1345836/

### .rt
_Output Example_
.rt the dark knight rises
**RT** | The Dark Knight Rises | 87% | 8/10 |  290 ↑/44  ↓ | https://www.rottentomatoes.com/m/the_dark_knight_rises/

### .tv
_Output Example_
.tv fargo
**TV** | Fargo | 2014- | Next Episode: The Law of Vacant Places (April 19, 2017) | An American black comedy–crime drama anthology television series created and primarily written by Noah Hawley... http://thetvdb.com/?tab=series&id=269613&lid=7

### .next
_Output Example_
.next Fargo
**TV** | Fargo | Next Episode: The Law of Vacant Places (April 19, 2017) | A petty sibling rivalry between two brothers escalates and brings chaos to a small Minnesotan community. http://thetvdb.com/?tab=episode&seriesid=269613&seasonid=701224&id=5978330&lid=7

### .m
_Use the moon command (after 'moonrunes') to look up Japanese equivalents of English words via jisho.org_
_Output Example_
.m what
**Jisho** | 何 |  なに | nani | what

### .j
_Use the jisho command to look up Japanese words (in romaji, hiragana, katakana or kanji) via jisho.org_
_Output Example_
.j nani
**Jisho** | 何 |  なに | nani | what

## And to make porygon2 a 100% obsolete is to use title output for websites
_Output Example_
https://github.com/464bb26bac556e85b6fd6b524347b103
**Title** | 464bb26bac556e85b6fd6b524347b103 | https://github.com/464bb26bac556e85b6fd6b524347b103

_YouTube Output_
https://www.youtube.com/watch?v=g8evyE9TuYk
**YouTube** | The Dark Knight Rises - Official Trailer #3 [HD] | 02:19 | 32,275,031 | Apr 30, 2012 | https://www.youtube.com/watch?v=g8evyE9TuYk

I don't know how is that faggot? Enough work **for you**?

**Comment by BlackPeopleSteal** [comment]
**Hello my white friends of zuck.**

_Regarding the Jisho.org output and how it should look._

> **Output Example:** Jisho | (Kanji) | (Kun) | (Romanji) | (English)
> **Input Command:** .j watashi
> **Example:** Jisho | 私 | わたくし | watashi | I; me

**.j** 
_This should be the Japanese word look up for example:_
_Results used via classic jisho search: http://classic.jisho.org/words?jap=watashi&eng=&dict=edict&romaji=on_
.j watashi
Jisho | 私 | わたくし | watashi | I; me

**.m**
_This should be the English meaning after the moonrunes for example:_

Watashi might show  I;me as result, but I and or me wont give you the result of 私
You need the search results via this link http://classic.jisho.org/words?jap=&eng=me&dict=edict&common=on 
Which will give you the desired result of the right kanji 私 and kun わたくし
Jisho | 私 | わたくし | watashi | I; me

**So I think this covers it right? I don't fucking know, just that the classic jisho is better than the new website.**

**Comment by BlackPeopleSteal** [comment]
## Wolfram Alpha

**.wa**

> **Output Example:** Wolfram Alpha | (Input interpretation) | (Result) |
> **Input Command:** .wa Jews in America
> **Example:** Wolfram Alpha | Judaism United States | 5.81 million people fraction of country population. - 1.9% fraction of all adherents. - 41%

**Comment by 464bb26bac556e85b6fd6b524347b103** [comment]
remaining features have been broken out into their own issues to keep things better organizzed

#11 - .wa
#12 - .m and .j
#13 - .help
#14 - url titles
